# -*- coding: utf-8 -*-
"""
concept_lexicon.py — The 25 tasavvuf concepts
=============================================
For each concept:
  key       — stable id (latin, lowercase)
  label_*   — display label in tr/en/ar/fa
  variants  — Arabic/Persian surface forms to match (after normalization).
              We match these as *whole-word stems* against normalized tokens,
              tolerating the definite article and a small set of proclitics.
  cat       — thematic family (used for colour grouping in the lens)
  zahir_*   — a one-line "what counting can/cannot reach" gloss (the
              zāhir/bāṭin caution that rides on every concept in the atlas)

The lexicon is deliberately conservative: high-frequency function-word-like
roots (e.g. ḏ-k-r "to mention", q-l-b "heart/to turn") are included because
they are genuine technical terms here, but the DATA_DICTIONARY documents the
homograph caveat. Counting is a coarse proxy; it maps the word, not the ḥāl.
"""

# cat families
# tecrübe  = experiential/states (hāl, vecd, …)   — the most bāṭin
# bilgi    = knowing/unveiling (mārifet, keşf, …)
# son      = ends of the path (fenâ, bekâ, tevhîd)
# ahlak    = ethical stations (zühd, sabır, …)
# amel     = practice (zikir, semâ, halvet, …)
# kurum    = social/institutional (şeyh, mürid, velî, silsile)

CONCEPTS = [
    # ── ends of the path ───────────────────────────────────────────────
    {"key": "fena", "cat": "son",
     "label_tr": "Fenâ", "label_en": "Fanāʾ", "label_ar": "فناء", "label_fa": "فنا",
     "variants": ["فناء", "فنا", "فاني", "افناء", "يفنى", "فنيت"],
     "zahir_tr": "Sözcüğü sayabiliriz; Cüneyd'in fenâ tecrübesini sayamayız.",
     "zahir_en": "We can count the word; not Junayd's lived fanāʾ.",
     "zahir_ar": "نُحصي اللفظَ لا الفناءَ المُعاش.",
     "zahir_fa": "واژه را می‌شماریم، نه فنای زیسته را."},
    {"key": "beka", "cat": "son",
     "label_tr": "Bekâ", "label_en": "Baqāʾ", "label_ar": "بقاء", "label_fa": "بقا",
     "variants": ["بقاء", "بقا", "باقي", "يبقى", "ابقاء"],
     "zahir_tr": "Fenâ'dan sonra bekâ: harita ardışıklığı gösterir, hâli değil.",
     "zahir_en": "Subsistence after annihilation: the map shows sequence, not state.",
     "zahir_ar": "البقاء بعد الفناء: تُظهر الخريطةُ التتابعَ لا الحالَ.",
     "zahir_fa": "بقا پس از فنا: نقشه توالی را نشان می‌دهد نه حال را."},
    {"key": "tevhid", "cat": "son",
     "label_tr": "Tevhîd", "label_en": "Tawḥīd", "label_ar": "توحيد", "label_fa": "توحید",
     "variants": ["توحيد", "توحید", "وحدانية", "موحد", "احدية", "وحدت"],
     "zahir_tr": "İlmî tevhîd yazıya geçer; tevhîdin zevki geçmez.",
     "zahir_en": "Doctrinal tawḥīd is written; the taste of it is not.",
     "zahir_ar": "توحيدُ العلمِ يُكتب؛ وذوقُه لا يُكتب.",
     "zahir_fa": "توحید علمی نوشته می‌شود؛ ذوق آن نه."},
    # ── knowing / unveiling ────────────────────────────────────────────
    {"key": "marifet", "cat": "bilgi",
     "label_tr": "Mârifet", "label_en": "Maʿrifa", "label_ar": "معرفة", "label_fa": "معرفت",
     "variants": ["معرفة", "معرفت", "عرفان", "عارف", "معارف", "يعرف", "عرف"],
     "zahir_tr": "Mârifet kelimesinin dağılımı görünür; mârifetin kendisi bâtın.",
     "zahir_en": "The distribution of 'maʿrifa' is visible; the gnosis itself is bāṭin.",
     "zahir_ar": "توزيعُ لفظِ المعرفة ظاهر؛ والمعرفةُ نفسُها باطنة.",
     "zahir_fa": "پراکندگی واژهٔ معرفت پیداست؛ خود معرفت باطنی است."},
    {"key": "kesf", "cat": "bilgi",
     "label_tr": "Keşf", "label_en": "Kashf", "label_ar": "كشف", "label_fa": "کشف",
     "variants": ["كشف", "کشف", "مكاشفة", "مکاشفه", "ينكشف", "انكشاف"],
     "zahir_tr": "Keşf bir hadisedir; metinde adı geçer, vâkıası değil.",
     "zahir_en": "Unveiling is an event; the text names it, not the event.",
     "zahir_ar": "الكشفُ واقعة؛ يَذكر النصُّ اسمَها لا عينَها.",
     "zahir_fa": "کشف رویدادی است؛ متن نامش را می‌برد نه خودش را."},
    # ── experiential states ────────────────────────────────────────────
    {"key": "hal", "cat": "tecrube",
     "label_tr": "Hâl", "label_en": "Ḥāl", "label_ar": "حال", "label_fa": "حال",
     "variants": ["حال", "احوال", "أحوال", "حالة", "حالات"],
     "zahir_tr": "Hâl tanımı en zorudur: sayım onu en çok ıskalar.",
     "zahir_en": "'State' is the hardest to define: counting misses it most.",
     "zahir_ar": "الحالُ أعصى على التعريف: والإحصاءُ أبعدُ ما يكون عنه.",
     "zahir_fa": "حال دشوارترین برای تعریف است: شمارش بیش از همه آن را از دست می‌دهد."},
    {"key": "vecd", "cat": "tecrube",
     "label_tr": "Vecd", "label_en": "Wajd", "label_ar": "وجد", "label_fa": "وجد",
     "variants": ["وجد", "وجدان", "مواجيد", "تواجد", "يجد"],
     "zahir_tr": "Vecd bir an'dır; frekansı bize sıklığı verir, anı değil.",
     "zahir_en": "Ecstasy is a moment; frequency gives us its rate, not the moment.",
     "zahir_ar": "الوجدُ لحظة؛ يعطينا التواترُ معدّلَها لا اللحظةَ.",
     "zahir_fa": "وجد لحظه‌ای است؛ بسامد نرخ آن را می‌دهد نه لحظه را."},
    {"key": "ask", "cat": "tecrube",
     "label_tr": "Aşk", "label_en": "ʿIshq", "label_ar": "عشق", "label_fa": "عشق",
     "variants": ["عشق", "عاشق", "معشوق", "عشاق", "يعشق"],
     "zahir_tr": "Attâr ve Mevlânâ'da yoğunlaşır; sayı eğilimi gösterir, ateşi değil.",
     "zahir_en": "Peaks in ʿAṭṭār and Rūmī; the count shows the trend, not the fire.",
     "zahir_ar": "يَشتدّ عند العطار ومولانا؛ يُظهر العددُ المنحى لا النار.",
     "zahir_fa": "در عطار و مولانا اوج می‌گیرد؛ عدد روند را نشان می‌دهد نه آتش را."},
    {"key": "mahabbet", "cat": "tecrube",
     "label_tr": "Mahabbet", "label_en": "Maḥabba", "label_ar": "محبة", "label_fa": "محبت",
     "variants": ["محبة", "محبت", "محب", "حب", "احباب", "يحب", "محبوب"],
     "zahir_tr": "Mahabbet hem ahlâkî makam hem hâl; iki yüzü ölçüye sığmaz.",
     "zahir_en": "Love is both ethical station and state; neither face fits a metric.",
     "zahir_ar": "المحبةُ مقامٌ خُلقي وحالٌ معًا؛ ولا وجهَ منهما يَسَعه القياس.",
     "zahir_fa": "محبت هم مقام اخلاقی است هم حال؛ هیچ‌یک در سنجه نمی‌گنجد."},
    {"key": "sevk", "cat": "tecrube",
     "label_tr": "Şevk", "label_en": "Shawq", "label_ar": "شوق", "label_fa": "شوق",
     "variants": ["شوق", "اشتياق", "مشتاق", "يشتاق", "اشواق"],
     "zahir_tr": "Şevk özlemdir; metin onu anar, özlemin acısını taşımaz.",
     "zahir_en": "Longing aches; the text names it without carrying the ache.",
     "zahir_ar": "الشوقُ لوعة؛ يَذكره النصُّ ولا يَحمل لوعتَه.",
     "zahir_fa": "شوق دردِ اشتیاق است؛ متن نامش را می‌برد بی‌آنکه درد را حمل کند."},
    # ── ethical stations ───────────────────────────────────────────────
    {"key": "zuhd", "cat": "ahlak",
     "label_tr": "Zühd", "label_en": "Zuhd", "label_ar": "زهد", "label_fa": "زهد",
     "variants": ["زهد", "زاهد", "تزهد", "يزهد", "زهاد"],
     "zahir_tr": "Zühd dışsal davranışta görünür: ölçüye en yatkın makam.",
     "zahir_en": "Asceticism shows in outward conduct: the most measurable station.",
     "zahir_ar": "يَظهر الزهدُ في السلوك الظاهر: أقربُ المقامات إلى القياس.",
     "zahir_fa": "زهد در رفتار بیرونی پیداست: سنجش‌پذیرترین مقام."},
    {"key": "sabir", "cat": "ahlak",
     "label_tr": "Sabır", "label_en": "Ṣabr", "label_ar": "صبر", "label_fa": "صبر",
     "variants": ["صبر", "صابر", "يصبر", "اصطبار", "تصبر"],
     "zahir_tr": "Sabır süreçtir; frekans yoğunluğu verir, sürenin yükünü değil.",
     "zahir_en": "Patience is a process; frequency gives weight, not duration's burden.",
     "zahir_ar": "الصبرُ مسار؛ يُعطي التواترُ الثقلَ لا عبءَ المدّة.",
     "zahir_fa": "صبر فرایند است؛ بسامد وزن می‌دهد نه بار مدت را."},
    {"key": "tevekkul", "cat": "ahlak",
     "label_tr": "Tevekkül", "label_en": "Tawakkul", "label_ar": "توكل", "label_fa": "توکل",
     "variants": ["توكل", "توکل", "متوكل", "يتوكل", "متوكلين"],
     "zahir_tr": "Tevekkül kalbî bir tutumdur; sözcüğü dışsaldır, tutumu değil.",
     "zahir_en": "Trust is an inner posture; the word is outward, the posture is not.",
     "zahir_ar": "التوكلُ هيئةٌ قلبية؛ اللفظُ ظاهر والهيئةُ ليست كذلك.",
     "zahir_fa": "توکل حالتی قلبی است؛ واژه بیرونی است نه آن حالت."},
    {"key": "riza", "cat": "ahlak",
     "label_tr": "Rızâ", "label_en": "Riḍā", "label_ar": "رضا", "label_fa": "رضا",
     "variants": ["رضا", "رضى", "راض", "يرضى", "مرضاة", "رضوان"],
     "zahir_tr": "Rızâ bir kabûldür; metinde işâreti var, zevki yok.",
     "zahir_en": "Contentment is an acceptance; the text holds its sign, not its taste.",
     "zahir_ar": "الرضا قبول؛ في النصِّ علامتُه لا ذوقُه.",
     "zahir_fa": "رضا پذیرش است؛ در متن نشانه‌اش هست نه ذوقش."},
    {"key": "havf", "cat": "ahlak",
     "label_tr": "Havf", "label_en": "Khawf", "label_ar": "خوف", "label_fa": "خوف",
     "variants": ["خوف", "خائف", "يخاف", "مخافة", "خشية"],
     "zahir_tr": "Havf–recâ çifti birlikte okunur; sayım onları ayırır ama dengeyi söylemez.",
     "zahir_en": "Fear–hope is a pair; counting separates them but can't state the balance.",
     "zahir_ar": "الخوفُ والرجاءُ زوج؛ يَفصلهما العدُّ ولا يُبيّن التوازن.",
     "zahir_fa": "خوف و رجا جفت‌اند؛ شمارش جدایشان می‌کند اما تعادل را نمی‌گوید."},
    {"key": "reca", "cat": "ahlak",
     "label_tr": "Recâ", "label_en": "Rajāʾ", "label_ar": "رجاء", "label_fa": "رجا",
     "variants": ["رجاء", "رجا", "يرجو", "راج", "ارتجاء"],
     "zahir_tr": "Recâ umuttur; Ensârî'de zirve yapar — yine de bir frekanstır.",
     "zahir_en": "Hope; it peaks in al-Anṣārī — yet remains a frequency.",
     "zahir_ar": "الرجاءُ أمل؛ يَبلغ ذروتَه عند الأنصاري — ويبقى تواترًا.",
     "zahir_fa": "رجا امید است؛ در انصاری اوج می‌گیرد — و باز بسامدی است."},
    # ── practice ───────────────────────────────────────────────────────
    {"key": "zikir", "cat": "amel",
     "label_tr": "Zikir", "label_en": "Dhikr", "label_ar": "ذكر", "label_fa": "ذکر",
     "variants": ["ذكر", "ذکر", "اذكار", "يذكر", "ذاكر", "مذاكرة", "تذكر"],
     "zahir_tr": "‘Ẕikr’ hem ‘anma’ hem teknik terim — homografi sayımı şişirir (bk. sözlük).",
     "zahir_en": "'Dhikr' is both 'to mention' and the technical term — homography inflates the count (see dictionary).",
     "zahir_ar": "الذكرُ لفظٌ عامّ ومصطلح؛ والاشتراكُ يَنفخ العددَ (انظر المعجم).",
     "zahir_fa": "ذکر هم «یاد کردن» است هم اصطلاح؛ هم‌نگاری عدد را باد می‌کند (نک. واژه‌نامه)."},
    {"key": "sema", "cat": "amel",
     "label_tr": "Semâ", "label_en": "Samāʿ", "label_ar": "سماع", "label_fa": "سماع",
     "variants": ["سماع", "يسمع", "سامع", "مساع"],
     "zahir_tr": "Semâ işitme/dinleme âyini; sözcük çok-anlamlı, törenin ruhu sayıya gelmez.",
     "zahir_en": "Samāʿ is the listening rite; the word is polysemous, the rite's spirit uncountable.",
     "zahir_ar": "السماعُ طقسُ الإصغاء؛ اللفظُ مشترك وروحُ الطقس لا تُعدّ.",
     "zahir_fa": "سماع آیین شنیدن است؛ واژه چندمعناست و روح آیین شمردنی نیست."},
    {"key": "halvet", "cat": "amel",
     "label_tr": "Halvet", "label_en": "Khalwa", "label_ar": "خلوة", "label_fa": "خلوت",
     "variants": ["خلوة", "خلوت", "خلوات", "اعتزال", "يخلو"],
     "zahir_tr": "Halvet bir mekân-pratiğidir; metinde geçer, içinde ne olduğu değil.",
     "zahir_en": "Seclusion is a spatial practice; the text records it, not what happens within.",
     "zahir_ar": "الخلوةُ ممارسةٌ مكانية؛ يُسجّلها النصُّ لا ما يجري فيها.",
     "zahir_fa": "خلوت کرداری مکانی است؛ متن آن را ثبت می‌کند نه آنچه در آن می‌گذرد."},
    # ── soul / heart (anthropology) ────────────────────────────────────
    {"key": "nefs", "cat": "tecrube",
     "label_tr": "Nefs", "label_en": "Nafs", "label_ar": "نفس", "label_fa": "نفس",
     "variants": ["نفس", "انفس", "أنفس", "نفوس", "نفساني"],
     "zahir_tr": "Nefs korpusun en sık kavramı; sıklık tema ağırlığını gösterir, mücâhedeyi değil.",
     "zahir_en": "The corpus's most frequent concept; frequency shows thematic weight, not the struggle.",
     "zahir_ar": "أكثرُ مفاهيم المدوّنة ورودًا؛ يُظهر التواترُ الثقلَ الموضوعي لا المجاهدة.",
     "zahir_fa": "پربسامدترین مفهوم پیکره؛ بسامد وزن موضوعی را نشان می‌دهد نه مجاهده را."},
    {"key": "kalp", "cat": "tecrube",
     "label_tr": "Kalp", "label_en": "Qalb", "label_ar": "قلب", "label_fa": "قلب",
     "variants": ["قلب", "قلوب", "قلبي", "فؤاد", "افئدة"],
     "zahir_tr": "‘Qalb’ ‘kalp’ ve ‘çevirmek’ — homografi (bk. sözlük); tasavvufî merkez yine de güçlü.",
     "zahir_en": "'Qalb' is 'heart' and 'to turn' — homography (see dict.); still a strong Sufi centre.",
     "zahir_ar": "القلبُ عضوٌ وتقليب؛ اشتراك (انظر المعجم)؛ والمركزُ الصوفي قوي مع ذلك.",
     "zahir_fa": "قلب هم «دل» است هم «گرداندن» — هم‌نگاری (نک. واژه‌نامه)؛ با این حال مرکزی صوفیانه."},
    # ── institutions / persons ─────────────────────────────────────────
    {"key": "veli", "cat": "kurum",
     "label_tr": "Velî / Evliyâ", "label_en": "Walī / Awliyāʾ", "label_ar": "ولي / أولياء", "label_fa": "ولی / اولیا",
     "variants": ["ولي", "أولياء", "اولياء", "اولیا", "ولاية", "ولایت", "ولي الله"],
     "zahir_tr": "Velâyet kurumsal-tarihsel; ağ haritalanır, velînin sırrı haritalanmaz.",
     "zahir_en": "Sainthood is institutional-historical; the network maps, the walī's secret does not.",
     "zahir_ar": "الولايةُ تاريخية-مؤسسية؛ تُرسَم الشبكةُ ولا يُرسَم سرُّ الولي.",
     "zahir_fa": "ولایت نهادی-تاریخی است؛ شبکه نقشه می‌شود نه راز ولی."},
    {"key": "murid", "cat": "kurum",
     "label_tr": "Mürid", "label_en": "Murīd", "label_ar": "مريد", "label_fa": "مرید",
     "variants": ["مريد", "مرید", "مريدين", "مريدون", "ارادة", "اراده"],
     "zahir_tr": "Mürid–şeyh ekseni sosyal yapı; aktarım çizgesi bunu yakalar.",
     "zahir_en": "The murīd–shaykh axis is social structure; the transmission graph catches it.",
     "zahir_ar": "محورُ المريد والشيخ بنيةٌ اجتماعية؛ يَلتقطه مخططُ النقل.",
     "zahir_fa": "محور مرید و شیخ ساختار اجتماعی است؛ نمودار انتقال آن را می‌گیرد."},
    {"key": "seyh", "cat": "kurum",
     "label_tr": "Şeyh / Pîr", "label_en": "Shaykh / Pīr", "label_ar": "شيخ", "label_fa": "شیخ / پیر",
     "variants": ["شيخ", "شیخ", "مشايخ", "مشایخ", "شيوخ", "پير", "پیر"],
     "zahir_tr": "Şeyh otoritesi silsilede görünür; rehberliğin kendisi sayıya gelmez.",
     "zahir_en": "The shaykh's authority shows in the silsila; the guidance itself is uncountable.",
     "zahir_ar": "تَظهر سلطةُ الشيخ في السلسلة؛ والإرشادُ نفسُه لا يُعدّ.",
     "zahir_fa": "اقتدار شیخ در سلسله پیداست؛ خود ارشاد شمردنی نیست."},
]
